# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2021 Novateck, Inc
#

obj-$(CONFIG_DISP_IF8B_LCD1_PW35P00_HX8238D) += disp_if8b_lcd1_pw35p00_hx8238d/
obj-$(CONFIG_DISP_IF8B_LCD1_AUCN01) += disp_if8b_lcd1_aucn01/
obj-$(CONFIG_DISP_IF8B_LCD1_PSD300) += disp_if8b_lcd1_psd300_ili8961/
obj-$(CONFIG_DISP_IF8B_LCD1_TP2803) += disp_if8b_lcd1_tp2803/
obj-$(CONFIG_DISP_IFDSI_LCD1_UT35067A0) += disp_ifdsi_lcd1_ut35067a0_ili9488/
obj-$(CONFIG_VIDEO_LOGO) += pinctrl-nvt-plat.o na51055_pinmux_host.o dispdev_panlcomn.o dispdev_platform.o
